/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        volt: {
          DEFAULT: '#D4FF4F',
          bright: '#E2FF7A',
          deep: '#B8E62E',
          ink: '#0A0F00',
          soft: 'rgba(212,255,79,0.08)',
          line: 'rgba(212,255,79,0.22)',
          dim: 'rgba(212,255,79,0.15)',
        },
        base: '#0A0A0B',
        raised: '#101013',
        surface: '#121416',
        /* Stitch HeyGym Discovery tokens (source of truth) */
        'surface-container-lowest': '#0c0e10',
        'surface-container-low': '#1a1c1e',
        'surface-container': '#1e2022',
        'surface-container-high': '#282a2c',
        'surface-container-highest': '#333537',
        'surface-variant': '#333537',
        'surface-bright': '#38393c',
        'surface-dim': '#121416',
        'surface-tint': '#b0d500',
        primary: {
          DEFAULT: '#ffffff',
          container: '#caf300',
          fixed: '#caf300',
          'fixed-dim': '#b0d500',
        },
        'primary-container': '#caf300',
        'primary-fixed': '#caf300',
        'primary-fixed-dim': '#b0d500',
        'on-primary': '#2a3400',
        'on-primary-fixed': '#171e00',
        'on-primary-fixed-variant': '#3e4c00',
        'on-primary-container': '#596c00',
        'inverse-primary': '#536600',
        secondary: {
          DEFAULT: '#c2c6d1',
          container: '#424750',
          fixed: '#dee2ee',
          'fixed-dim': '#c2c6d1',
        },
        'secondary-container': '#424750',
        'secondary-fixed': '#dee2ee',
        'secondary-fixed-dim': '#c2c6d1',
        'on-secondary': '#2c3139',
        'on-secondary-container': '#b1b5c0',
        'on-secondary-fixed': '#171c24',
        'on-secondary-fixed-variant': '#424750',
        tertiary: {
          DEFAULT: '#ffffff',
          container: '#6ffbbe',
          fixed: '#6ffbbe',
          'fixed-dim': '#4edea3',
        },
        'tertiary-container': '#6ffbbe',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary': '#003824',
        'on-tertiary-container': '#00734e',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        'on-surface': '#e2e2e5',
        'on-surface-variant': '#c5c9ac',
        'on-background': '#e2e2e5',
        'inverse-surface': '#e2e2e5',
        'inverse-on-surface': '#2f3033',
        background: '#121416',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        outline: '#8f9378',
        'outline-variant': '#444932',
        card: '#141417',
        overlay: '#0C0C0E',
      },
      fontFamily: {
        display: ['var(--font-display)', '"Plus Jakarta Sans"', 'sans-serif'],
        sans: ['var(--font-sans)', '"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'display-hero': ['"Plus Jakarta Sans"', 'sans-serif'],
        'display-hero-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-xl': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-xl-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-xs-mono': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'display-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'display-hero-mobile': ['38px', { lineHeight: '44px', letterSpacing: '-0.025em', fontWeight: '800' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'headline-xl-mobile': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '30px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', letterSpacing: '0em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '0.005em', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-xs-mono': ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      spacing: {
        gutter: '1.5rem',
        'gutter-sm': '1rem',
        margin: '2rem',
        'margin-mobile': '1rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
      },
      borderRadius: {
        input: '10px',
        card: '16px',
        modal: '20px',
      },
      boxShadow: {
        premium: '0 1px 0 rgba(255,255,255,0.05) inset, 0 12px 32px rgba(0,0,0,0.45), 0 2px 8px rgba(0,0,0,0.4)',
        raised: '0 1px 0 rgba(255,255,255,0.06) inset, 0 20px 50px rgba(0,0,0,0.5)',
        volt: '0 1px 0 rgba(212,255,79,0.2) inset, 0 8px 24px rgba(212,255,79,0.18)',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
      animation: {
        marquee: 'marquee 24s linear infinite',
      },
    },
  },
  plugins: [],
};